### ISSUE TITLE
parte13

### ISSUE THREAD

**Issue by Rikardo-Baptista** [miguelriemoliveira/psr_23-24#11]
Bom dia professor,

Está em falta apontamentos da aula13 e também a gravação da parte12.

Obrigado.

**Comment by miguelriemoliveira** [comment]
Olá @Rikardo-Baptista , boa tarde,

já estou a fazer o upload da gravação da aula 12. Deve estar disponível em breve no youtube.

Quanto aos apontamentos da aula13, já coloquei online.
