### ISSUE TITLE
Problemas com a adição de uma camara numa base rotativa

### ISSUE THREAD

**Issue by PedroMaia21** [miguelriemoliveira/psr_23-24#12]
Para o trabalho 3, tenho tentado por uma câmara estática numa base rotativa no robô. Ao fazer os elos, e a adicionar os frames de referência da camâra e da lente (literalmente a copiar os elos respetivos à camara que já vinha com o turtlebot) tenho tido um problema. Ao lançar o Rviz, os sistemas de coordenadas e as tranfosrmações aparentam estar bem, no entanto a câmara não parece estar a publicar no tópico que lhe pedi. Andei por muito tempo à procura do problema e descobri que se eu removesse por completo as transformações geométricas (ou seja, associando o a câmara ao base_link) esta já funcionava. Isto poderia ser a solução, se eu quisesse uma câmara estática, o que não é o caso. 
Também procurei em fóruns, mas sem sucesso, porque parece ser um problema muito específico... Se o professor tiver alguma iidea de como resolver este problema, ficaria muito agradecido!

**Comment by miguelriemoliveira** [comment]
Olá @PedroMaia21 ,

parece estranho. Pode partilhar link para o seu xacro. Se for privado adicione-me como colaborador ao repositório.

**Comment by PedroMaia21** [comment]
Vou enviar o link para o [repositório](https://github.com/PedroMaia21/PSR_TP3.git). O que eu acrescentei foi a partir da linha 225 (robutler.urdf.xacro) e a partir da linha 180 (robutler.gazebo.xacro)

**Comment by miguelriemoliveira** [comment]
Olá @PedroMaia21 ,

Uma dica: para ajudar quem o vai ajudar, o melhor é colocar um link para a linha, em vez de dizer onde é e obrigar a pessoa a estar à procura.

Por exemplo:

https://github.com/PedroMaia21/PSR_TP3/blob/c51ce424bc43d6df4dcf9fcc6e45219c1bc9d9cf/robutlerT3G1_description/urdf/robutlerT3G1.urdf.xacro#L180-L292

**Comment by miguelriemoliveira** [comment]
Olá @PedroMaia21 ,

diga-me por favor como preciso de fazer para replicar o seu erro, quer dizer, que comando corre quando lhe dá o erro?

Já descarreguei o seu repo, só preciso de saber como ver o erro ...

**Comment by miguelriemoliveira** [comment]
Aqui vai um exemplo de como reportar um erro de modo a que os outros o possam replicar

https://github.com/lardemua/atom/issues/792

**Comment by PedroMaia21** [comment]
> Olá @PedroMaia21 ,
> 
> diga-me por favor como preciso de fazer para replicar o seu erro, quer dizer, que comando corre quando lhe dá o erro?
> 
> Já descarreguei o seu repo, só preciso de saber como ver o erro ...

É quando se lança os dois ficheiros .launch (gazebo.launch e bringup.launch, por essa ordem).
Mas na verdade eu não contabilizei como erro... Foi apenas um comportamento inesperado

**Comment by miguelriemoliveira** [comment]
Olá @PedroMaia21 , 

desculpe a insistência, mas a ideia é mesmo ensinar-lhe a forma correta de pedir ajuda. 

Eu não quero que me diga como devo fazer desta forma.

Pense que cada segundo de quem o está a ajudar (a maioria das vezes voluntariamente) é precioso. Devemos por isso poupar o mais possível o tempo de quem nos ajuda. Se não o fizermos o mais provável é que as pessoas pura e simplesmente desistam de nos ajudar.

Quando diz isto assim:

> É quando se lança os dois ficheiros .launch (gazebo.launch e bringup.launch, por essa ordem).

Obriga-me a ir ao seu repo, procurar estes ficheiros, perceber como é que os chamo ver se precisam de argumentos, etc etc.

A forma como deve dizer é:

Primeiro lanço este comando:

    roslaunch robutlerT3G1_bringup gazebo.launch

Depois este 

   roslaunch robutlerT3G1_bringup bringup.launch

e o erro que aparece é:

```terminal
blablbalba
```

Assim só tenho de fazer dois copy pastes, e estou logo apta a ajudá-lo.

> Mas na verdade eu não contabilizei como erro... Foi apenas um comportamento 

Esta parte não percebi. Quer mesmo ajuda para resolver isto ou não?

> inesperado

**Comment by PedroMaia21** [comment]
sim, quero ajuda.
Então, ao executar o comando
`roslaunch robutlerT3G1_bringup gazebo.launch`
e ao lançar 
`roslaunch robutlerT3G1_bringup bringup.launch`
eu esperaria ver, quando executado o 
`rostopic list`
um tópico chamado '/camera/rgb/image2_raw' mas tal não acontece.
No entanto ao substituir `"rotating_camera_link"` por `"base_link"` na seguinte linha (https://github.com/PedroMaia21/PSR_TP3/blob/c51ce424bc43d6df4dcf9fcc6e45219c1bc9d9cf/robutlerT3G1_description/urdf/robutlerT3G1.urdf.xacro#L267C19-L267C39) já há mensagens a serem publicadas nesse tópico (e consequentemente uma visualização gráfica no Rviz)

**Comment by miguelriemoliveira** [comment]
Olá @PedroMaia21 ,

consigo correr o seu código e replicar o erro.

**Comment by miguelriemoliveira** [comment]
A árvore de transformações parece bem

![image](https://github.com/miguelriemoliveira/psr_23-24/assets/11350998/414b5faf-6464-49f3-aeea-8c07e84c539d)

**Comment by miguelriemoliveira** [comment]
e daí não tenho a certeza ... esta parte parece estranha 

![image](https://github.com/miguelriemoliveira/psr_23-24/assets/11350998/2a23fb2c-e397-4edb-8a60-15f26ca4e7c7)


parece que a última transformação do rotating base para o rotating camera foi há 300 segundos ... é estranho ...

**Comment by miguelriemoliveira** [comment]
talvez o problem não seja este, visto que a transformação da hodometria do gazebo mostra o mesmo padrão

![image](https://github.com/miguelriemoliveira/psr_23-24/assets/11350998/ae8cb1c3-a2eb-423e-9b9c-f843b6582b75)

**Comment by miguelriemoliveira** [comment]
Continuo sem perceber o problema. 

Estive a ver o xacro e não veja nada de mal (exceto o nome das câmaras com espaços, mas esse não parece ser o problema)

Tente usar este exemplo multicâmara. Este sei que funciona bem.

https://github.com/lardemua/atom/tree/noetic-devel/atom_examples/rrbot

**Comment by PedroMaia21** [comment]
Estive a tentar com essa mudança nos ficheiros xacro [(ver commit)](https://github.com/PedroMaia21/PSR_TP3/commit/a077d5eacb93c23ec8731b18a4d6f82243fa4a93), mas infelizmente ao usar o 
/rostopic list
apenas consigo ver o tópico '/rgb_rotating/image_raw' quando os elos que queria rotativos estão fixos ( [elo da base rotativa](https://github.com/PedroMaia21/PSR_TP3/blob/a077d5eacb93c23ec8731b18a4d6f82243fa4a93/robutlerT3G1_description/urdf/robutlerT3G1.urdf.xacro#L238C48-L238C48) e [elo rotativo para a câmara](https://github.com/PedroMaia21/PSR_TP3/blob/a077d5eacb93c23ec8731b18a4d6f82243fa4a93/robutlerT3G1_description/urdf/robutlerT3G1.urdf.xacro#L259C43-L259C43) )
Neste momento não sei o que mais tentar...

**Comment by PedroMaia21** [comment]
Afinal tive progressos, com a tentativa que fiz depois deste ultimo comentario.
Ao que parece, apenas o parent link da câmara é que tem de estar fixo (gostava ainda de saber porque, mas o pior já está resolvido) porque assim que eu pûs o [elo da base rotativa ](https://github.com/PedroMaia21/PSR_TP3/blob/a077d5eacb93c23ec8731b18a4d6f82243fa4a93/robutlerT3G1_description/urdf/robutlerT3G1.urdf.xacro#L238C48-L238C48) como revolute mantendo o outro fixed, já funcionou
Assim sendo, vou cirar um elo imaginário para ser o parent link da câmara

**Comment by miguelriemoliveira** [comment]
Boa @PedroMaia21 ,

ainda bem que resolveu. Eu realmente tinha vários exemplos de câmaras a mexer, e nunca tive estes problemas. 

Por exemplo neste exemplo uma das câmaras está montada no end-effector de um manipulador robótico

https://github.com/lardemua/atom/tree/noetic-devel/atom_examples/rihbot

**Comment by PedroMaia21** [comment]
Afinal o problema não ficou resolvido...
No entanto ao ver este [Vídeo no youtube](https://www.youtube.com/watch?v=Y5K4gF2teIA) apercebi-me de onde poderia estar o problema.
Ao que parece, para utilizar o gazebo, se se fizer mais que uma junta consecutiva, tem de se adicionar os parâmetros de inércia aos links, senão ele não os coloca no modelo.
Por isso, agora sim, o problema está resolvido

**Comment by miguelriemoliveira** [comment]
Obrigado @PedroMaia21 pelo cuidado de dizer como resolveu. Assim pode ajudar os colegas que tenham eventualmente o mesmo problema.
