### ISSUE TITLE
Problema com o gazebo

### ISSUE THREAD

**Issue by VMTG** [miguelriemoliveira/psr_23-24#15]
Boa noite, professor @miguelriemoliveira 

Relativamente à sua reposta ao meu email hoje de tarde, já consigo correr os ficheiros .launch, contudo não me aparece o mapa do trabalho no gazebo, aparece-me apenas o robô.

Quando executo primeiro o rviz e depois o gazebo, aparece logo a seguir um erro no terminal do rviz.

Abaixo apresento o respetivo erro:

"[FATAL] [1704409589.163573069, 1.495000000]: Failed to create the dwa_local_planner/DWAPlannerROS planner, are you sure it is properly registered and that the containing library is built? Exception: According to the loaded plugin descriptions the class dwa_local_planner/DWAPlannerROS with base class type nav_core::BaseLocalPlanner does not exist. Declared types are  base_local_planner/TrajectoryPlannerROS
[move_base-6] process has died [pid 29264, exit code 1, cmd /opt/ros/noetic/lib/move_base/move_base cmd_vel:=/cmd_vel odom:=odom __name:=move_base __log:=/home/vitor/.ros/log/b864fb60-ab54-11ee-a58f-b7c6c2ac6d40/move_base-6.log].
log file: /home/vitor/.ros/log/b864fb60-ab54-11ee-a58f-b7c6c2ac6d40/move_base-6*.log"

**Comment by miguelriemoliveira** [comment]
Já instalou o dwa planner?

    sudo apt-get install ros-noetic-dwa-local-planner*

**Comment by VMTG** [comment]
Depois de instalar o dwa planner deixou de aparecer o erro referido inicialmente, mas continua a não aparecer o mapa do trabalho.

**Comment by miguelriemoliveira** [comment]
Veja o vídeo da aula e tente repetir os passos. Já adicionou o mapa no rviz?

**Comment by VMTG** [comment]
Já vi os videos mas não percebo como conseguir resolver o problema. Sim, aparece o mapeamento do mapa no rviz, apenas não aparece o mapa no gazebo.

**Comment by miguelriemoliveira** [comment]
Mas já acrescentou o marker para o mapa no rviz?

Tem de me dar mais detalhes,  caso contrário só consigo adivinhar qual
poderá ser o erro.

Se está a seguir o vídeo passo por passo então diga-me em que parte falha
...

**Comment by VMTG** [comment]
Quando executo o bringup.launch e em seguida o gazebo.launch ambos funcionam, bem como o teleop para conduzir o robot. Simplesmente, o mapa não é carregado no gazebo.

Em anexo envio duas fotos para ilustrar o que acontece.

![WhatsApp Image 2024-01-05 at 16 06 24](https://github.com/miguelriemoliveira/psr_23-24/assets/145006280/1c6a1b33-9ae1-48c7-9982-18eca6684f7b)
![WhatsApp Image 2024-01-05 at 16 06 25](https://github.com/miguelriemoliveira/psr_23-24/assets/145006280/8227b481-2d6b-4b9b-b9a7-0c407fca3b9b)

**Comment by miguelriemoliveira** [comment]
Já fez o mapa com slam?

**Comment by VMTG** [comment]
O mapa que aparece no rviz foi feito por um dos membros do meu grupo. Ele meteu o trabalho num repositório no github para trabalharmos, eu fiz git clone do trabalho e quando fui a executar o trabalho, só aparecia o mapa mapeado no rviz e não aparecia o mapa no gazebo. Eu já alterei o caminho no gazepo para usar o mapa que eu tenho, mas mesmo assim o mapa não é carregado.

**Comment by miguelriemoliveira** [comment]
Olá @VMTG ,

não percebo muito bem. O mapa não aparece no gazebo ... está a falar do mapa gerado pelo SLAM, certo?

Indique o vídeo e o minuto em que vê o mapa no gazebo?

**Comment by VMTG** [comment]
Não me estou a conseguir explicar muito bem por escrito, porque também não percebo onde poderá estar o erro/problema.
Sendo assim, seria possivel marcar uma reunião zoom com o professor para mostrar o problema e tentar resolver?

**Comment by VMTG** [comment]
Boa tarde professor,

Felizmente, já consegui resolver o problema.
Obrigado pela ajuda!

**Comment by miguelriemoliveira** [comment]
Boas notícias. Não quer explicar qual era o problema e como o resolveu? Pode ajudar outros colegas ...

**Comment by VMTG** [comment]
Basicamente, o problema estava a acontecer porque tinha vários ficheiros com o mesmo nome. Aleterei isso e resolveu!

**Comment by miguelriemoliveira** [comment]
OK. Obrigado.
