### ISSUE TITLE
Modelos spawnados não são afetados com física e não têm colisões 

### ISSUE THREAD

**Issue by PedroMaia21** [miguelriemoliveira/psr_23-24#19]
Boa tarde professor, ao realizar testes com o robutler, mais em concretamente com o script que usámos nas aulas, reparei que os objetos que forem invocados com um valor de z superior ao pretendido acabam a pairar no ar emvez de serem afetados pela gravidade. Para além disso, quando o robô tem de passar por um desses objetos na execução de uma movimentação autónoma, acaba por passar através deles, para além de que estes objetos não aparecem detetados nos valores lidos pelo  laser scan, o que é deveras estranho.

O tracking deste problema tem sido feito neste [issue](https://github.com/PedroMaia21/PSR_TP3/issues/21)

O script de spawn é o seguinte [(script)](https://github.com/PedroMaia21/PSR_TP3/blob/main/robutler1_bringup/scripts/spawn_object.py) 

E a pasta onde os modelos estão incluídos é [esta](https://github.com/PedroMaia21/PSR_TP3/tree/main/robutler1_description/models)

O que me deixa mais perplexo foi o uso do modelo da aula (neste caso nomeado sphere_r) que deveria estar operacional. Mas realmente na aula não experimentámos invocá-lo 'a pairar' e por sua vez não foi possível verificar o seu funcionamento

**Comment by PedroMaia21** [comment]
Afinal era mais simples do que o que eu julgava. Os objetos estavam a ser spawnados com a check_box "is_static" ativada. Ou seja eles tinham uma tag <static> com o valor de 1, e esta deveria ser 0. Já procedi com as alterações necessárias

**Comment by PedroMaia21** [comment]
> Afinal era mais simples do que o que eu julgava. Os objetos estavam a ser spawnados com a check_box "is_static" ativada. Ou seja eles tinham uma tag com o valor de 1, e esta deveria ser 0. Já procedi com as alterações necessárias
 *com uma tag `<static>`

**Comment by miguelriemoliveira** [comment]
A tag static para mim explica o fato de os objetos não serem afetados pela gravidade, mas a parte das colisões ainda me intriga ...

**Comment by miguelriemoliveira** [comment]
> Pode ter sido apenas uma impressão que tive, na verdade não vi o modelo 3d a colidir com nenhum objeto, mas quando passou perto de uma bola a imagem da camara parecia que tinha entrado por dentro da bola, e isto pode ser explicado pelo facto da colisão das câmaras ser uma caixa pequena

OK. Vou então fechar o issue.
