### ISSUE TITLE
Gravação da Aula 9 PSR

### ISSUE THREAD

**Issue by Rikardo-Baptista** [miguelriemoliveira/psr_23-24#7]
Bom dia professor,

Não se encontra disponibilizado a gravação da Aula 9 PSR na sua pagina Youtube.

Obrigado

**Comment by miguelriemoliveira** [comment]
Olá @Rikardo-Baptista ,

Vou fazer upload agora. Deve estar daqui a 30 mins.

**Comment by Rikardo-Baptista** [comment]
Boa noite, professor,
Já se encontra disponivel a gravação da Aula9, mas a qualidade está em 360p pelo que não é nada perceptivel.

Obrigado

**Comment by miguelriemoliveira** [comment]
Olá Ricardo,

depois de fazer upload, o youtube processa o vídeo durante umas horas e, durante esse período, disponibiliza o vídeo apenas com baixa qualidade.

Agora acho que está bem.

Abraço,
Miguel

**Comment by Rikardo-Baptista** [comment]
Olá professor

Pensei que o professor por lapso tivesse colocado com a resolução baixa.
Agora o video está bem.

Obrigado
Ricardo
