### ISSUE TITLE
Catking_make

### ISSUE THREAD

**Issue by GustavoReggio** [miguelriemoliveira/psr_23-24#9]
Olá, não sei dizer bem ao certo quando, mas de uns tutoriais para cá (estou no 15, Examining the Simple Service and Client) quando faço cc, catiking_make, me aparece o seguinte erro:
Alguém tem alguma ideia ?
![Captura de ecrã 2023-11-22 172023](https://github.com/miguelriemoliveira/psr_23-24/assets/145671022/408ee02d-0803-48c0-8126-cecc6bc4bc18)

**Comment by GustavoReggio** [comment]
catkin_make***

**Comment by miguelriemoliveira** [comment]
Olá Gustavo,

parece que tem algum problem no seu pacote begginner_tutorials. 

Consegue enviar um printscreen com os ficheiros que estão nessa pasta?

**Comment by GustavoReggio** [comment]
Olá Professor, entretanto um colega entrou em contato comigo e consegui resolver, muito obrigado pela preocupação e atenção.
Desculpa ter tomado tempo do professor.

**Comment by miguelriemoliveira** [comment]
Obrigado Gustavo. Sugiro que coloque aqui a solução que encoutrou para ajudar os colegas.

**Comment by GustavoReggio** [comment]
Dentro da CMakeLists.txt :
arrumar para a seguinte forma:

catkin_install_python(PROGRAMS scripts/talker.py
  DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
)
catkin_install_python(PROGRAMS scripts/add_two_ints_server.py scripts/add_two_ints_client.py
  DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
)
